"""empty message

Revision ID: ffc1018d5f80
Revises: bad80b7f28da
Create Date: 2021-09-06 09:01:13.139826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc1018d5f80'
down_revision = 'bad80b7f28da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['product.name'], ),
    sa.ForeignKeyConstraint(['price'], ['product.price'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.CHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('cart')
    # ### end Alembic commands ###
